### ISSUE TITLE
Incorrect autoloader / namespace

### ISSUE THREAD

**Issue by swissspidy** [lukasfischer/openinbound-api#1]
According to the [composer.json](https://github.com/lukasfischer/openinbound-api/blob/763b066be88476b7b29f1ab7e6409553587e63b8/composer.json#L16-L20) file, all classes within the `OpenInbound` namespace can be found in the `src` folder.

There are two problems with this definition:

1. The only class so far is within `src/API`, so one level deeper than what Composer expects.
2. The `OI` class does not have any [namespace declaration](https://github.com/lukasfischer/openinbound-api/blob/763b066be88476b7b29f1ab7e6409553587e63b8/src/API/OI.php#L1-L6) at all.

This means autoloading can't really work.

**Comment by lukasfischer** [comment]
@swissspidy, I fixed the namespace declaration.
